version: 3.9
services:
  web:
    build:
      context: ./web/
      dockerfile: dockerfile.web
      env_file:
        - .env
      ports:
        - 3000:3000
  backend:
    build:
      context: ./backend/
      dockerfile: dockerfile.backend
    env_file:
      - .env
    ports:
      - 5000:5000
  worker:
    build:
      context: ./backend/
      dockerfile: dockerfile.worker
    env_file:
      - .env
  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
  database:
    image: postgres:15.1
    ports:
      - '3306:3306'
